Added tests for the project - part two
YuriShumanski1980/SalesForceProject pull request #2
Opened 2021-08-17 22:54 UTC by YuriShumanski1980

2021-08-18 20:03 UTC, vchesnakou requested changes
please make fixes

2021-08-18 20:03 UTC, vchesnakou commented on src/main/java/pages/AccountPage.java
> +        log.info("Select account & click dropdown");
в логе указывай параметры, кот. ты передаешь (accountName)

2021-08-18 20:03 UTC, vchesnakou commented on src/main/java/pages/AccountPage.java
> +    @Step("Click dropdown")
в степе указывай параметры, кот. ты передаешь (accountName)

2021-08-18 20:03 UTC, vchesnakou commented on src/main/java/pages/AccountPage.java
> +    public AccountPage clickDropDown(String accountName) {
clickDropDownForAccountName

2021-08-18 20:03 UTC, vchesnakou commented on src/main/java/pages/AccountPage.java
> +    }
модалы - это отдельные страницы

2021-08-18 20:03 UTC, vchesnakou commented on src/main/java/pages/AccountPage.java
> +    public boolean elementIsNotPresent(String accountName){
isElementPresent,

 return !driver.findElements(By.xpath(ACCOUNT_NAME_ON_ACCOUNT_PAGE)).isEmpty();

2021-08-18 20:03 UTC, vchesnakou commented on src/main/java/pages/NewTaskModalPage.java
> +    private static final String TASK_SUBJECT = "//*[@class ='row row-main column']//descendant::span[contains(., '%s')]";
@class ='row row-main column - тут привязка к 3 классам сразу, можно ли сделать к какому-то одному ?

2021-08-18 20:03 UTC, vchesnakou commented on src/main/java/pages/NewTaskModalPage.java
> +    private static final String TASK_DUE_DATE = "//*[contains(@class, 'slds-col slds-grid')]//span[contains(@class, 'slds-grow')][contains(., '%s')]";
тут тоже

2021-08-18 20:03 UTC, vchesnakou commented on src/main/java/pages/NewTaskModalPage.java
> +    private static final String TASK_REMINDER_SET = "//*[@class = 'slds-form-element__control slds-grid itemBody']//span[contains(., '%s')]";
и тут. 

Это не надежные локаторы

2021-08-18 20:03 UTC, vchesnakou commented on src/main/java/pages/NewTaskModalPage.java
> +        new Input(driver, "Reminder Set").clickReminderSet();
передавай в логи параметры

2021-08-18 20:03 UTC, vchesnakou commented on src/main/java/pages/NewTaskModalPage.java
> +        new DropDown(driver, "Priority").select(priority);
также передавай параметры в лог

2021-08-20 18:28 UTC, vchesnakoutest approved these changes

2021-08-21 20:38 UTC, merged